config/routes.rb
MongoReport::Application.routes.draw do

  devise_for :users

  resources :reports
  root :to => "reports#index"

  match '/all_report', to: 'reports#admin_report_list'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
     if user.admin?
        can :manage, :all
    else
        can :you ,User
        can :show, User
        can :update, User , :id => user.id

     end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/example.rb
class Example
  include Mongoid::Document
end

app/models/report.rb
class Report
  include Mongoid::Document

  ##Report Fields

  field :title, type: String
  field :body_text, type: String
  field :public_flag, type: Boolean
  field :report_date, type: Date


  ##Reration
  belongs_to  :user

  attr_accessible :title, :body_text, :user_id,
                :report_date, :public_flag

  def public_flag?
      public_flag == true
  end

end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation,
                  :remember_me, :name, :role, :send_address

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time

  ## User's Field
  field :name, type: String
  field :send_address , type: String
  field :role, type: String

  ## Reration
  has_many :reports

  ## Methods
  def admin?
    role == "ADMIN" #これ定数で呼び出ししたかったなあ
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
  check_authorization
end

app/controllers/reports_controller.rb
#coding:utf-8

class ReportsController < ApplicationController
  def index
    @reports = current_user.reports
    #@reports =  Report.all# Scaffold Code
    respond_to do |format|

      format.html # index.html.erb
      format.json { render json: @reports }
    end
  end

  def admin_report_list
    @reports =  Report.all
    respond_to do |format|

      format.html # index.html.erb
      format.json { render json: @reports }
    end
  end

  def month_list
    #TODO: add month Fillter and public Fillter
  end


 def new
    @report = Report.new()
    #@report.worktimes.build
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @report }
    end
  end

  def create
    #@report = Report.new(params[:report])#Scaffold code
    @report = current_user.reports.new(params[:report])
    respond_to do |format|
      if @report.save

        #ApplicationController.helpers.sending_report_submit(@report.user,@report)

        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render json: @report, status: :created, location: @report }
      else
        format.html { render action: "new" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @report = Report.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @report }
    end
  end

  def destroy
    @report = Report.find(params[:id])
    @report.destroy

    respond_to do |format|
      format.html { redirect_to reports_path }
      format.json { head :no_content }
    end
  end


  # GET /reports/1/edit
  def edit
    @report = Report.find(params[:id])
  end

    def update
    @report = Report.find(params[:id])

    respond_to do |format|
      if @report.update_attributes(params[:report])
        #ApplicationController.helpers.sending_report_submit(@report.user,@report)

        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_grobal_header.html.erb
#coding:utf-8

<div class = "site_header" >
    <div class = "logo">
        <h2>日報アプリケーション</h2>
    </div>
    <%if signed_in? %>
        <div class = "log_in_user">
            <% if Rails.env.development? %>
                <!-- 開発時に表示 -->
                userID:[<%="#{current_user.id}" %> ]
                Admin:[<%="#{current_user.admin?}" %> ]
                <br>
            <% end%>
            ユーザーの名前[ <%="#{current_user.name}"%> ]
            E-mail:[<%="#{current_user.email}"%>]

            <% if current_user.admin? %>
                <%= link_to "Report List(Admin)", all_report_path%>
                <%= link_to "User list(Admin)", '#'%>
            <% end %>

            <%= button_to "Sign out", destroy_user_session_path, :method => :delete %>
        </div>
    <% else %>
        サインインしてください<br>
    <% end %>
    <hr>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MongoReport</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/grobal_header'%>

<%= yield %>

</body>
</html>

app/views/reports/_create_form.html.erb
#coding:utf-8

<%= form_for(@report) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <!-- 日報の入力フィールド -->
  <div class="date_field">
    <%= f.label "報告日付" %><br />
    <%= f.date_select(
        :report_date,
        use_month_numbers: true,
        start_year: 2014,
        default: Date.today() )%>
  </div>

  <div class="input_text_field">
    <%= f.label "題名" %><br />
    <%= f.text_field :title %>
  </div>
  <div class="input_text_field">
    <%= f.label "本文" %><br />
    <%= f.text_area :body_text %>
  </div>

  <div class="field">
    <%= f.label "公開フラグ" %><br />
    <%= f.check_box :public_flag, {}, true, false %>
  </div>

  <div class="actions">
    <%= f.submit(['save report',]) %>
  </div>

<% end %>

app/views/reports/_report_list_button.html.erb
#coding:utf-8
<%= link_to 'report-index', reports_path %>

app/views/reports/_report_listing_form.html.erb
#coding:utf-8

<%#= stylesheet_link_tag "list_page", :media => "all" %>


<% unless @reports.length == 0%>
  <table class = "test1">

    <tr>
      <th>公開</th>
      <th>日報ID</th>
      <th>報告日付</th>
      <th>タイトル</th>
      <th>本文(最初の10文字)</th>
      <th>著者ID</th>
      <th>著者名</th>
      <th>閲覧</th>
      <th>編集</th>
      <th>削除</th>
      <th>あなたの日報か？</th>
    </tr>

    <% @reports.each do |report| %>
      <tr>
        <td><%= report.public_flag? ? "O" : "X"%></td>
        <td><%= report.id%></td>
        <td><%= report.report_date%></td>
        <td><%= report.title %></td>
        <td><%= report.body_text.slice(0,10) %></td>
        <td><%= report.user_id %></td>
        <td><%= report.user.name %></td>

        <td><%= button_to 'Show', report_path(report),method: :get %></td>
        <td><%= button_to 'Edit', edit_report_path(report),method: :get %></td>
        <td><%= button_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%if current_user.id == report.user_id %>
              <%= "O"%>
            <%else%>
               <%= "X"%>
            <%end%>
        </td>
      </tr>
    <% end %>
  </table>
<% else %>
  <h2> まだ日報がありません </h2>
<% end%>

app/views/reports/admin_report_list.html.erb
#coding:utf-8

<h1>全ての日報</h1>

<%= render 'report_listing_form' %>

app/views/reports/edit.html.erb
<h1>Editing report</h1>

<%= render 'create_form' %>

<%= link_to 'Show', @report %>
<%= render 'report_list_button' %>

app/views/reports/index.html.erb
#coding:utf-8

<h1>月報リスト予定地</h1>

<%= render 'report_listing_form' %>

<%= button_to 'Create Report', new_report_path, method: :get %>

app/views/reports/new.html.erb
#coding:utf-8

<h1>日報新規作成</h1>

<%= render 'create_form' %>

app/views/reports/show.html.erb
#coding:utf-8
<p id="notice"><%= notice %></p>
  <div class = "show_text">
    <b>Date:</b>
    <%= @report.report_date %>
  </div>

  <div class = "show_text">
    <b>Title:</b>
    <%= @report.title %>
  </div>


  <div class = "show_text">
    <b>Bodytext:</b>
    <%= @report.body_text %>
  </div>

  <div class = "show_text">
    <b>公開状態</b>
    <%= @report.public_flag? ? "O" : "X"%>
  </div>
<%= link_to 'Edit', edit_report_path(@report) %>
<%= render 'report_list_button' %>